version: "3.8"
services:
  quietquillapi:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: QuietQuillAPI/Dockerfile
    depends_on:
      - bedb
    restart: unless-stopped
    networks:
      qqn:
        ipv4_address: 10.56.1.2

  bedb:
    image: mysql:8.0.21
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: quietquill
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: quietquill
      MYSQL_PASSWORD: 12345678
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - ./mysql:/var/lib/mysql
    command: [
      "--default-authentication-plugin=mysql_native_password"
    ]
    restart: always
    networks:
      qqn:
        ipv4_address: 10.56.1.3

  fe:
    image: yunka19/quietquill-fe:latest
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - quietquillapi
    networks:
      qqn:
        ipv4_address: 10.56.1.4

networks:
  qqn:
    ipam:
      config:
        - subnet: "10.56.1.0/24"
