version: "1"
services:
  quietquillapi:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: QuietQuillAPI/Dockerfile
    depends_on: 
      - bedb
    restart: no
    networks:
      qqn:
         ipv4_address: 10.56.1.2
  bedb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MQSQL_DATABASE: quietquilllc
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./mysql:/var/lib/mysql 
    restart: always
    networks:
      qqn:
        ipv4_address: 10.56.1.3

  fe:
    image: dockerusername/volume-name
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - quietquillapi
    networks:
      qqn:
        ipv4_address: 10.56.1.4
        
networks:
  qqn:
    ipam:
      driver: default
      config:
        - subnet: "10.56.1.0/24"      
        