name: SonarScanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: self-hosted

    env:
      DOTNET_ROOT: ${{ github.workspace }}/.dotnet
      PATH: ${{ github.workspace }}/.dotnet:$PATH:/usr/bin
      SONAR_HOST_URL: http://localhost:9000
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore QuietQuillBE/QuietQuillBE.sln

      - name: Build project
        run: dotnet build --no-restore --configuration Release QuietQuillBE/QuietQuillBE.sln

      - name: Run tests
        run: dotnet test --no-build --configuration Release QuietQuillBE/QuietQuillBE.sln

      - name: Prepare SonarQube Scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:$HOME/.dotnet/tools"
          echo "PATH after tool installation: $PATH"

      - name: Run SonarQube Scan
        run: |
          dotnet tool run dotnet-sonarscanner begin /k:"QuietQuill-be" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.login="$SONAR_TOKEN" /s:"QuietQuillBE/QuietQuillBE.sln"
          dotnet build QuietQuillBE/QuietQuillBE.sln
          dotnet tool run dotnet-sonarscanner end /d:sonar.login="$SONAR_TOKEN"
